"""``/v1/tenants`` tenant-provisioning endpoint — Stream P (Mini-ADR P-1/P-2/P-5).

``POST /v1/tenants`` is the explicit "create a tenant" action. It is a
**platform-level** operation — provisioning a brand-new RLS scope — so it is
gated on ``is_system_admin`` directly (Mini-ADR P-2: a tenant ADMIN must not
be able to mint other tenants, hence no ``tenant`` RBAC resource). The write
runs inside :func:`bypass_rls_session` because the new ``tenant_id`` differs
from the caller's request-scoped ``app.tenant_id`` and the FORCE-RLS
``tenant_config`` policy would otherwise reject the insert.

Listing/reading/configuring an existing tenant lives in ``tenant_config`` /
``tenant_quotas`` (which share this ``/v1/tenants`` prefix); the bare
``POST ""`` here does not collide with their ``{tenant_id}/...`` paths.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Annotated, Self
from uuid import UUID, uuid4

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, ConfigDict, Field, model_validator

from control_plane.api._authz import _principal
from control_plane.api.first_admin import (
    FirstAdminConflictError,
    FirstAdminKeycloakUnavailableError,
    provision_first_admin,
)
from control_plane.audit import emit
from control_plane.keycloak import KeycloakAdminClient
from control_plane.runtime import AgentRuntime
from control_plane.settings import Settings
from control_plane.tenant_scope import bypass_rls_session
from control_plane.tenant_status import TenantStatusService
from helix_agent.common.observability import current_trace_id_hex
from helix_agent.persistence.auth import RoleBindingStore
from helix_agent.persistence.tenant_config.base import (
    TenantConfigAlreadyExistsError,
    TenantConfigNotFoundError,
    TenantConfigStore,
)
from helix_agent.persistence.tenant_member import TenantMemberStore
from helix_agent.protocol import AuditAction, Principal, TenantPlan
from helix_agent.runtime.audit.logger import AuditLogger
from helix_agent.runtime.runs import RunStatus, RunStore

logger = logging.getLogger("helix.control_plane.api.tenants")


class CreateTenantRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    # Server-generated by default; a client-supplied UUID supports idempotent
    # provisioning from an upstream system (Mini-ADR P-5).
    tenant_id: UUID | None = None
    display_name: str = Field(min_length=1, max_length=128)
    plan: TenantPlan | None = None
    # Stream R W1 — provision the company's first admin in the same step.
    # ``None`` creates a bare tenant (backwards compatible). email uses a plain
    # ``str`` + light validation (Mini-ADR R-12: no email-validator dependency).
    first_admin_email: str | None = Field(default=None, max_length=320)
    first_admin_display_name: str | None = Field(default=None, max_length=128)

    @model_validator(mode="after")
    def _validate_first_admin(self) -> Self:
        if self.first_admin_display_name and not self.first_admin_email:
            raise ValueError("first_admin_display_name requires first_admin_email")
        if self.first_admin_email is not None:
            email = self.first_admin_email.strip()
            if "@" not in email or email.startswith("@") or email.endswith("@"):
                raise ValueError("first_admin_email is not a valid email address")
            object.__setattr__(self, "first_admin_email", email.lower())
        return self


def _get_repo(request: Request) -> TenantConfigStore:
    return request.app.state.tenant_config_repo  # type: ignore[no-any-return]


def _get_audit(request: Request) -> AuditLogger:
    return request.app.state.audit_logger  # type: ignore[no-any-return]


def _get_member_repo(request: Request) -> TenantMemberStore:
    return request.app.state.tenant_member_repo  # type: ignore[no-any-return]


def _get_role_binding_repo(request: Request) -> RoleBindingStore:
    return request.app.state.role_binding_repo  # type: ignore[no-any-return]


def _get_keycloak(request: Request) -> KeycloakAdminClient:
    return request.app.state.keycloak_admin_client  # type: ignore[no-any-return]


def _get_settings(request: Request) -> Settings:
    return request.app.state.settings  # type: ignore[no-any-return]


def _get_tenant_status_service(request: Request) -> TenantStatusService:
    return request.app.state.tenant_status_service  # type: ignore[no-any-return]


def _get_run_store(request: Request) -> RunStore:
    return request.app.state.run_store  # type: ignore[no-any-return]


def _get_runtime(request: Request) -> AgentRuntime:
    return request.app.state.agent_runtime  # type: ignore[no-any-return]


#: Stream RT-4 — page size + hard cap for the tenant-suspend bulk-cancel scan.
#: ``list_for_tenant`` clamps ``limit`` to 500 (MAX_LIST_LIMIT), so pages are
#: 500 rows; the cap bounds a pathological tenant with a huge in-flight set.
_BULK_CANCEL_PAGE = 500
_MAX_BULK_CANCEL_RUNS = 5000


async def _bulk_cancel_tenant_runs(
    *,
    tenant_id: UUID,
    run_store: RunStore,
    runtime: AgentRuntime,
    audit: AuditLogger,
    actor_id: str,
    trace_id: str | None,
) -> int:
    """Stream RT-4 (RT-ADR-17) — terminate a suspended tenant's in-flight runs.

    Enumerate the tenant's RUNNING *and* PENDING runs (both are in-flight;
    ``RunManager.cancel`` / ``request_cancel`` guard to those two statuses)
    across paginated reads, and stop each. A run THIS instance owns aborts
    immediately (abort_event + status CAS); a run held by another instance is
    guarded-cancelled in the store (running/pending → interrupted), so that
    worker's next lease heartbeat CAS fails and it stops within one heartbeat
    interval — ``request_cancel`` never clobbers a run that just finished. Each
    cancel emits a ``SESSION_CANCEL`` audit row under the enclosing
    ``TENANT_DEACTIVATE``. The listing runs inside the caller's
    ``bypass_rls_session`` (the target tenant is not the system-admin caller's
    home tenant).
    """
    # Gather RUNNING + PENDING ids first (paginated), THEN cancel — cancelling
    # flips status out of running/pending, which would shift a live offset scan
    # and skip rows. Bounded by ``_MAX_BULK_CANCEL_RUNS``; hitting the cap is
    # logged (no silent truncation) so an operator can re-run suspend.
    run_ids: list[UUID] = []
    capped = False
    for status in (RunStatus.RUNNING, RunStatus.PENDING):
        offset = 0
        while len(run_ids) < _MAX_BULK_CANCEL_RUNS:
            page = await run_store.list_for_tenant(
                tenant_id=tenant_id,
                status=status,
                limit=_BULK_CANCEL_PAGE,
                offset=offset,
            )
            run_ids.extend(r.run_id for r in page)
            if len(page) < _BULK_CANCEL_PAGE:
                break
            offset += _BULK_CANCEL_PAGE
        if len(run_ids) >= _MAX_BULK_CANCEL_RUNS:
            capped = True
            break
    if capped:
        logger.warning(
            "tenant_suspend.bulk_cancel_capped tenant_id=%s cap=%d",
            tenant_id,
            _MAX_BULK_CANCEL_RUNS,
        )
    cancelled = 0
    now = datetime.now(UTC)
    for run_id in run_ids:
        # Local run: aborts immediately. Peer-owned run: guarded store CAS
        # (running/pending → interrupted) so its next heartbeat fails and it stops.
        stopped = await runtime.run_manager.cancel(run_id) or await run_store.request_cancel(
            run_id=run_id, tenant_id=tenant_id, updated_at=now
        )
        if stopped:
            cancelled += 1
            await emit(
                audit,
                tenant_id=tenant_id,
                actor_id=actor_id,
                action=AuditAction.SESSION_CANCEL,
                resource_type="run",
                resource_id=str(run_id),
                trace_id=trace_id,
                reason="tenant_suspended",
            )
    return cancelled


def build_tenants_router() -> APIRouter:
    router = APIRouter(prefix="/v1/tenants", tags=["tenants"])

    @router.post("", status_code=201)
    async def create_tenant(
        payload: CreateTenantRequest,
        principal: Annotated[Principal, Depends(_principal)],
        repo: Annotated[TenantConfigStore, Depends(_get_repo)],
        audit: Annotated[AuditLogger, Depends(_get_audit)],
        member_repo: Annotated[TenantMemberStore, Depends(_get_member_repo)],
        role_binding_repo: Annotated[RoleBindingStore, Depends(_get_role_binding_repo)],
        keycloak: Annotated[KeycloakAdminClient, Depends(_get_keycloak)],
        settings: Annotated[Settings, Depends(_get_settings)],
    ) -> dict[str, object]:
        # Mini-ADR P-2 — tenant creation is platform-level; only system admins.
        if not principal.is_system_admin:
            raise HTTPException(
                status_code=403,
                detail={
                    "code": "PLATFORM_SCOPE_FORBIDDEN",
                    "message": "only a system admin may create tenants",
                },
            )
        tenant_id = payload.tenant_id or uuid4()
        # The new tenant_id is not the caller's home tenant, so the write +
        # its audit row must bypass RLS (Mini-ADR P-1, risk: audit-in-bypass).
        # Stream R W1 — the tenant row + (optional) first-admin roster row are
        # both written in this one bypass session so the local state is atomic
        # (Mini-ADR R-4 DB-first); the Keycloak side follows, with compensation.
        first_admin = None
        async with bypass_rls_session():
            try:
                record = await repo.create(
                    tenant_id=tenant_id,
                    display_name=payload.display_name,
                    plan=payload.plan,
                    actor_id=principal.subject_id,
                )
            except TenantConfigAlreadyExistsError as exc:
                raise HTTPException(
                    status_code=409,
                    detail={
                        "code": "TENANT_ALREADY_EXISTS",
                        "message": "a tenant with this id already exists",
                    },
                ) from exc
            await emit(
                audit,
                tenant_id=tenant_id,
                actor_id=principal.subject_id,
                action=AuditAction.TENANT_CREATE,
                resource_type="tenant",
                resource_id=str(tenant_id),
                trace_id=current_trace_id_hex(),
                details={"display_name": record.display_name, "plan": record.plan.value},
            )

            if payload.first_admin_email is not None:
                try:
                    result = await provision_first_admin(
                        tenant_id=tenant_id,
                        email=payload.first_admin_email,
                        display_name=payload.first_admin_display_name,
                        actor_id=principal.subject_id,
                        member_store=member_repo,
                        role_binding_store=role_binding_repo,
                        keycloak=keycloak,
                        audit=audit,
                        email_action_lifespan_s=settings.keycloak_email_action_lifespan_s,
                    )
                except FirstAdminConflictError as exc:
                    # Tenant is created; the email collides in Keycloak. The admin
                    # retries with a different email (Mini-ADR R-11).
                    raise HTTPException(
                        status_code=409,
                        detail={
                            "code": "MEMBER_KEYCLOAK_CONFLICT",
                            "message": "first admin email already exists; retry with another",
                        },
                    ) from exc
                except FirstAdminKeycloakUnavailableError as exc:
                    # Tenant + invited roster row exist; resend finishes Keycloak.
                    raise HTTPException(
                        status_code=502,
                        detail={
                            "code": "KEYCLOAK_UNAVAILABLE",
                            "message": "tenant created; admin account pending — retry via resend",
                        },
                    ) from exc
                first_admin = {
                    "member_id": str(result.member_id),
                    "email": result.email,
                    "status": result.status,
                    "keycloak_user_id": result.keycloak_user_id,
                }
        # ``data`` stays the tenant record (backwards compatible with Stream P
        # callers that read ``data.tenant_id`` / ``data.display_name``); the
        # first-admin summary is a sibling field, present only when requested.
        data = record.model_dump(mode="json")
        if first_admin is not None:
            data["first_admin"] = first_admin
        return {"success": True, "data": data, "error": None}

    @router.get("")
    async def list_tenants(
        principal: Annotated[Principal, Depends(_principal)],
        repo: Annotated[TenantConfigStore, Depends(_get_repo)],
        settings: Annotated[Settings, Depends(_get_settings)],
        limit: int = 50,
        offset: int = 0,
    ) -> dict[str, object]:
        """List all tenants (summary). Platform-level: system_admin only."""
        # Mirror create_tenant's gate (Mini-ADR P-2): listing tenants is a
        # cross-tenant platform read, so it requires system admin and a
        # bypass-RLS session (FORCE-RLS tenant_config would filter to the
        # caller's home tenant otherwise).
        if not principal.is_system_admin:
            raise HTTPException(
                status_code=403,
                detail={
                    "code": "PLATFORM_SCOPE_FORBIDDEN",
                    "message": "only a system admin may list tenants",
                },
            )
        capped = max(1, min(limit, 200))
        async with bypass_rls_session():
            records = await repo.list_all(limit=capped, offset=max(0, offset))
        return {
            "success": True,
            "data": [
                {
                    "tenant_id": str(r.tenant_id),
                    "display_name": r.display_name,
                    "plan": r.plan.value,
                    "status": r.status,
                    "created_at": r.created_at.isoformat(),
                    # The synthetic platform tenant (owns platform-level shared
                    # resources, reached via the ``*`` scope) is flagged so the
                    # admin UI can hide it from the customer-tenant list +
                    # switcher. The row stays in the API response so cross-tenant
                    # consumers keep a complete view.
                    "is_platform": r.tenant_id == settings.platform_tenant_id,
                }
                for r in records
            ],
            "error": None,
        }

    async def _set_tenant_status(
        tenant_id: UUID,
        status: str,
        action: AuditAction,
        *,
        principal: Principal,
        repo: TenantConfigStore,
        audit: AuditLogger,
        status_svc: TenantStatusService,
    ) -> dict[str, object]:
        # Mirror create_tenant/list_tenants (Mini-ADR P-2): changing a tenant's
        # lifecycle status is a platform-level action — system_admin only — and
        # the write + its audit row bypass RLS (the target tenant is not the
        # caller's home tenant; the FORCE-RLS tenant_config policy would reject
        # the UPDATE otherwise).
        if not principal.is_system_admin:
            raise HTTPException(
                status_code=403,
                detail={
                    "code": "PLATFORM_SCOPE_FORBIDDEN",
                    "message": "only a system admin may change tenant status",
                },
            )
        async with bypass_rls_session():
            try:
                await repo.set_status(
                    tenant_id=tenant_id, status=status, actor_id=principal.subject_id
                )
            except TenantConfigNotFoundError as exc:
                raise HTTPException(
                    status_code=404,
                    detail={"code": "TENANT_NOT_FOUND", "message": "tenant not found"},
                ) from exc
            await emit(
                audit,
                tenant_id=tenant_id,
                actor_id=principal.subject_id,
                action=action,
                resource_type="tenant",
                resource_id=str(tenant_id),
                trace_id=current_trace_id_hex(),
            )
        # Immediate effect on the writing instance; other replicas pick it up
        # within the cache TTL.
        status_svc.invalidate(tenant_id)
        return {
            "success": True,
            "data": {"tenant_id": str(tenant_id), "status": status},
            "error": None,
        }

    @router.post("/{tenant_id}/deactivate")
    async def deactivate_tenant(
        tenant_id: UUID,
        principal: Annotated[Principal, Depends(_principal)],
        repo: Annotated[TenantConfigStore, Depends(_get_repo)],
        audit: Annotated[AuditLogger, Depends(_get_audit)],
        status_svc: Annotated[TenantStatusService, Depends(_get_tenant_status_service)],
        run_store: Annotated[RunStore, Depends(_get_run_store)],
        runtime: Annotated[AgentRuntime, Depends(_get_runtime)],
    ) -> dict[str, object]:
        """Suspend a tenant — its members are 403'd until reactivated, and its
        in-flight runs are bulk-cancelled (Stream RT-4, RT-ADR-17)."""
        result = await _set_tenant_status(
            tenant_id,
            "suspended",
            AuditAction.TENANT_DEACTIVATE,
            principal=principal,
            repo=repo,
            audit=audit,
            status_svc=status_svc,
        )
        # RT-4 backfill — suspend previously only rejected NEW runs; now also
        # terminate in-flight ones. Same bypass-RLS scope as the status write
        # (target tenant ≠ the system-admin caller's home tenant). The response
        # contract is unchanged ({tenant_id, status}); each cancel is audited.
        async with bypass_rls_session():
            await _bulk_cancel_tenant_runs(
                tenant_id=tenant_id,
                run_store=run_store,
                runtime=runtime,
                audit=audit,
                actor_id=principal.subject_id,
                trace_id=current_trace_id_hex(),
            )
        return result

    @router.post("/{tenant_id}/activate")
    async def activate_tenant(
        tenant_id: UUID,
        principal: Annotated[Principal, Depends(_principal)],
        repo: Annotated[TenantConfigStore, Depends(_get_repo)],
        audit: Annotated[AuditLogger, Depends(_get_audit)],
        status_svc: Annotated[TenantStatusService, Depends(_get_tenant_status_service)],
    ) -> dict[str, object]:
        """Reactivate a suspended tenant."""
        return await _set_tenant_status(
            tenant_id,
            "active",
            AuditAction.TENANT_ACTIVATE,
            principal=principal,
            repo=repo,
            audit=audit,
            status_svc=status_svc,
        )

    return router
